// Code generated by "stringer -type=Brand"; DO NOT EDIT.

package car

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownBrand-0]
	_ = x[BMW-1]
	_ = x[Mercedes-2]
	_ = x[Audi-3]
	_ = x[Honda-4]
	_ = x[Toyota-5]
	_ = x[Volkswagon-6]
	_ = x[Ferrari-7]
	_ = x[Porsche-8]
	_ = x[Tesla-9]
}

const _Brand_name = "UnknownBrandBMWMercedesAudiHondaToyotaVolkswagonFerrariPorscheTesla"

var _Brand_index = [...]uint8{0, 12, 15, 23, 27, 32, 38, 48, 55, 62, 67}

func (i Brand) String() string {
	if i < 0 || i >= Brand(len(_Brand_index)-1) {
		return "Brand(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Brand_name[_Brand_index[i]:_Brand_index[i+1]]
}
