// Code generated by "stringer -type=Color"; DO NOT EDIT.

package car

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownColor-0]
	_ = x[Gray-1]
	_ = x[Green-2]
	_ = x[Yellow-3]
	_ = x[White-4]
	_ = x[Red-5]
}

const _Color_name = "UnknownColorGrayGreenYellowWhiteRed"

var _Color_index = [...]uint8{0, 12, 16, 21, 27, 32, 35}

func (i Color) String() string {
	if i < 0 || i >= Color(len(_Color_index)-1) {
		return "Color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
